include cmath instead of math.h
This is to fix the following compiler error:
fc/ppu/video.cpp:88:61: error: no member named 'pow' in namespace 'std'; did you mean simply 'pow'?