fix Cocoa uint conflict
sublime text 3 regexp search/replace:
find: uint(8|16|32|64)[^_]
replace: b$0

Here is an example of the conflict:
clang++ -x objective-c++ -std=c++14  -fwrapv -stdlib=libc++ -I. -I.. -O3 -march=native -DSFC_SUPERGAMEBOY -DPROFILE_ACCURACY -DVIDEO_CGL -DAUDIO_OPENAL -DINPUT_QUARTZ -DINPUT_CARBON  -c ../ruby/ruby.cpp -o obj/ruby.o
In file included from ../ruby/ruby.cpp:23:
In file included from /System/Library/Frameworks/Cocoa.framework/Headers/Cocoa.h:12:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:78:
In file included from /System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from /System/Library/Frameworks/Security.framework/Headers/Security.h:25:
/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:51:18: error: type alias redefinition with different types ('uint64_t' (aka 'unsigned long long') vs 'nall::Natural<64>')
typedef uint64_t uint64;
                 ^
../nall/primitives.hpp:346:7: note: previous definition is here
using uint64 = nall::Natural<64>;